-- =============================================================================
-- 07_T_ANON_TOY_POOL.sql
-- Pool table and pre-populated example data for the POOL anonymization method.
--
-- Values are fantasy-genre names and realistic-format but entirely fictional
-- identifiers.  They are intentionally identifiable as fake: no real person,
-- company, address, phone number, or account number is included.
--
-- Categories:
--   FIRST_NAME        Fantasy first names
--   LAST_NAME         Fantasy surnames
--   FULL_NAME         Pre-combined first + last (for columns storing full names)
--   COMPANY_NAME      Fantasy business names
--   CITY              Fantasy city names
--   STREET_ADDRESS    Fantasy street addresses
--   PHONE_HU          Hungarian format phone numbers  (+36 XX XXX XXXX)
--   PHONE_INTL        Various international formats
--   BANK_ACCOUNT_HU3  Hungarian 3-part account format  (NNNNNNNN-NNNNNNNN-NNNNNNNN)
--   BANK_ACCOUNT_HU2  Hungarian 2-part account format  (NNNNNNNN-NNNNNNNN)
--   IBAN              IBAN-format account numbers (structurally valid pattern, no real bank)
--   EMAIL             Fictional email addresses
--   DEPARTMENT        Fantasy department names
--   NATIONAL_ID_HU    Hungarian-style national ID format
--   NATIONAL_ID_EU    Generic EU national ID placeholders
--   TAX_NUMBER        Tax/VAT number placeholders
--   DIAGNOSIS_CODE    ICD-10-style codes with fantasy descriptions
--   MEDICATION        Fantasy-name medications with realistic dose formats
--   DOCTOR_NAME       Fantasy doctor names with title
--
-- Run as ANON_TOY after 06_T_ANON_TOY_LOG.sql.
-- =============================================================================

CREATE SEQUENCE SEQ_ANON_TOY_POOL_ID
    START WITH     1
    INCREMENT BY   1
    NOCACHE
    NOCYCLE;

CREATE TABLE T_ANON_TOY_POOL (
    ID          NUMBER(10)     DEFAULT SEQ_ANON_TOY_POOL_ID.NEXTVAL NOT NULL,
    CATEGORY    VARCHAR2(64)   NOT NULL,
    VALUE       VARCHAR2(4000) NOT NULL,
    MODIFIED    DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ANON_TOY_POOL PRIMARY KEY (ID)
);

CREATE INDEX IDX_ANON_TOY_POOL_CAT ON T_ANON_TOY_POOL (CATEGORY);

-- Prevent duplicate (CATEGORY, VALUE) pairs that would skew pool selection
-- probability by giving some values a higher-than-intended draw weight.
CREATE UNIQUE INDEX UQ_ANON_TOY_POOL_CAT_VAL
    ON T_ANON_TOY_POOL (CATEGORY, VALUE);

COMMENT ON TABLE  T_ANON_TOY_POOL IS
    'PKG_ANON_TOY pool table. Pre-populated replacement values for the POOL anonymization method.';
COMMENT ON COLUMN T_ANON_TOY_POOL.CATEGORY IS 'Value category. Must match DATA_CATEGORY in T_ANON_TOY_COLS for POOL method.';
COMMENT ON COLUMN T_ANON_TOY_POOL.VALUE    IS 'Replacement value drawn at random when the POOL method is applied.';


-- =============================================================================
-- Pool data
-- All names are original fantasy-genre inventions.
-- All numbers are structurally plausible but entirely fictional.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- FIRST_NAME (50 entries)
-- -----------------------------------------------------------------------------
INSERT ALL
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Aldric')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Caelindra')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Draven')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Eryndel')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Fyrath')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Galadwyn')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Haervyn')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Ithrial')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Jorethis')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Kaelveth')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Lyranthos')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Morvindel')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Naelith')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Oribeth')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Pyrindel')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Quelithar')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Rhosgal')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Sylthari')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Thaevon')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Ulyndra')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Vaelthorn')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Wytherin')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Xalavor')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Yndriel')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Zaephon')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Brythwen')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Caeldris')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Draveth')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Elorath')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Faelindra')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Gethwyn')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Holvindra')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Iravel')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Jorrindel')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Kytharis')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Liraeth')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Maevindra')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Nordwyn')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Orvindel')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Pethriel')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Quinrath')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Ryndavel')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Solithis')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Thaelvindra')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Uvindrel')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Vrynthis')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Waelindra')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Xyrindel')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Yoltharis')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FIRST_NAME', 'Zaelwyn')
SELECT 1 FROM DUAL;

-- -----------------------------------------------------------------------------
-- LAST_NAME (50 entries)
-- -----------------------------------------------------------------------------
INSERT ALL
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Ashveil')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Blackthorn')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Crestfall')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Darkwater')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Embervale')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Frostmere')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Grimhallow')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Highwatch')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Ironbrook')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Jadestone')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Kravenhold')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Lightweave')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Moonwhisper')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Nightglen')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Oakhaven')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Petravel')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Queensmere')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Ridgewood')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Stonefall')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Thornwick')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Umbervale')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Valewatch')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Whitefern')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Xanthorin')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Yarrowmere')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Zephyrholt')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Silvermont')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Ravenspire')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Duskmantle')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Cloudveil')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Bladewick')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Goldenfern')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Hearthvale')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Ironveil')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Jadecliff')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Kravenspire')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Lightmantle')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Moonveil')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Nightfall')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Oakenshade')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Pearlgate')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Queensveil')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Silvervale')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Thornbury')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Umbrastone')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Valewood')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Whiteglen')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Xythorin')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Yeldrim')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('LAST_NAME', 'Stormbrace')
SELECT 1 FROM DUAL;

-- -----------------------------------------------------------------------------
-- FULL_NAME (40 entries — first + last combinations)
-- -----------------------------------------------------------------------------
INSERT ALL
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Aldric Ashveil')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Caelindra Blackthorn')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Draven Crestfall')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Eryndel Darkwater')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Fyrath Embervale')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Galadwyn Frostmere')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Haervyn Grimhallow')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Ithrial Highwatch')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Jorethis Ironbrook')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Kaelveth Jadestone')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Lyranthos Kravenhold')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Morvindel Lightweave')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Naelith Moonwhisper')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Oribeth Nightglen')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Pyrindel Oakhaven')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Quelithar Petravel')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Rhosgal Queensmere')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Sylthari Ridgewood')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Thaevon Stonefall')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Ulyndra Thornwick')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Vaelthorn Umbervale')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Wytherin Valewatch')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Xalavor Whitefern')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Yndriel Xanthorin')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Zaephon Yarrowmere')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Brythwen Zephyrholt')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Caeldris Silvermont')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Draveth Ravenspire')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Elorath Duskmantle')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Faelindra Cloudveil')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Gethwyn Bladewick')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Holvindra Goldenfern')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Iravel Hearthvale')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Jorrindel Ironveil')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Kytharis Jadecliff')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Liraeth Kravenspire')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Maevindra Lightmantle')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Nordwyn Moonveil')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Orvindel Nightfall')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('FULL_NAME', 'Pethriel Stormbrace')
SELECT 1 FROM DUAL;

-- -----------------------------------------------------------------------------
-- COMPANY_NAME (30 entries)
-- -----------------------------------------------------------------------------
INSERT ALL
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Aetherstone Holdings')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Brightforge Industries')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Crystalveil Partners')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Dawnwatch Capital')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Embervault Financial')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Frostmantle Group')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Goldenveil Trust')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Highstone Consortium')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Ironveil Investments')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Jadespire Corp')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Kravenstone Advisory')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Lightforge Solutions')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Moonvault Securities')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Nightwatch Banking')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Opalgate Services')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Pearlspire Finance')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Queensvault Holdings')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Ridgewatch Partners')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Silverveil Capital')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Thorngate Group')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Umberveil Strategies')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Valespire Assets')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Whitegate Fund')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Xanthostone Ventures')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Yarrowspire Wealth')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Zephyrgate Holdings')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Arcveil Partners')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Bladestone Trust')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Crystalforge Capital')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('COMPANY_NAME', 'Dawnveil Advisory')
SELECT 1 FROM DUAL;

-- -----------------------------------------------------------------------------
-- CITY (30 entries)
-- -----------------------------------------------------------------------------
INSERT ALL
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Ashenvale')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Blackwater Bay')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Crystalmoor')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Dawnhaven')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Emberveil')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Frostpeak')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Goldenmere')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Highmantle')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Irongate')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Jadecliff')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Kravenspire')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Lightwater')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Moonridge')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Nightholm')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Oakenshade')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Pearlgate')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Queensmoor')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Ridgehaven')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Silvervale')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Thornbrook')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Umbervale')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Valewatch')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Whitefern')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Xanthorim')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Yarrowmere')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Zephyrholt')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Ashmont')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Bladewatch')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Crystalholm')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('CITY', 'Dawnspire')
SELECT 1 FROM DUAL;

-- -----------------------------------------------------------------------------
-- STREET_ADDRESS (30 entries)
-- -----------------------------------------------------------------------------
INSERT ALL
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '3 Ashwood Lane')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '17 Brightwater Avenue')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '42 Crystal Street')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '8 Dawning Road')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '91 Ember Path')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '5 Frostgate Way')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '23 Golden Square')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '66 Highwatch Boulevard')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '11 Ironwood Drive')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '34 Jade Court')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '78 Kravenhill Road')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '2 Lightspire Avenue')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '55 Moonveil Street')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '19 Nightgate Lane')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '47 Oakenshade Road')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '83 Pearlwater Way')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '6 Queensbridge Avenue')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '31 Ridgeway Drive')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '14 Silverbrook Lane')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '72 Thornfield Road')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '29 Umberveil Way')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '58 Valespire Court')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '4 Whiteglen Drive')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '96 Xanthorin Path')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '37 Yarrowfield Avenue')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '61 Zephyr Gate')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '18 Ashstream Way')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '44 Bladethorn Court')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '27 Crystal Hollow Lane')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('STREET_ADDRESS', '53 Dawnwatch Road')
SELECT 1 FROM DUAL;

-- -----------------------------------------------------------------------------
-- PHONE_HU — Hungarian format: +36 XX XXX XXXX  (20 entries)
-- -----------------------------------------------------------------------------
INSERT ALL
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_HU', '+36 20 123 4567')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_HU', '+36 30 234 5678')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_HU', '+36 70 345 6789')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_HU', '+36 20 456 7890')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_HU', '+36 30 567 8901')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_HU', '+36 70 678 9012')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_HU', '+36 20 789 0123')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_HU', '+36 30 890 1234')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_HU', '+36 70 901 2345')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_HU', '+36 20 012 3456')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_HU', '+36 30 123 9876')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_HU', '+36 70 234 8765')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_HU', '+36 20 345 7654')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_HU', '+36 30 456 6543')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_HU', '+36 70 567 5432')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_HU', '+36 20 678 4321')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_HU', '+36 30 789 3210')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_HU', '+36 70 890 2109')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_HU', '+36 20 901 1098')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_HU', '+36 30 012 0987')
SELECT 1 FROM DUAL;

-- -----------------------------------------------------------------------------
-- PHONE_INTL — International formats (20 entries)
-- -----------------------------------------------------------------------------
INSERT ALL
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_INTL', '+1 555 0142')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_INTL', '+1 555 0187')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_INTL', '+1 555 0263')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_INTL', '+44 7700 900142')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_INTL', '+44 7700 900187')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_INTL', '+44 7911 123456')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_INTL', '+49 30 12345678')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_INTL', '+49 89 87654321')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_INTL', '+33 1 23 45 67 89')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_INTL', '+41 44 123 45 67')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_INTL', '+31 20 123 4567')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_INTL', '+48 12 345 6789')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_INTL', '+43 1 234 5678')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_INTL', '+420 2 1234 5678')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_INTL', '+7 495 123-45-67')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_INTL', '+81 3-1234-5678')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_INTL', '+86 10 1234 5678')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_INTL', '+61 2 9876 5432')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_INTL', '+27 11 234 5678')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('PHONE_INTL', '+55 11 9876 5432')
SELECT 1 FROM DUAL;

-- -----------------------------------------------------------------------------
-- BANK_ACCOUNT_HU3 — Hungarian 3-part format: NNNNNNNN-NNNNNNNN-NNNNNNNN (20 entries)
-- -----------------------------------------------------------------------------
INSERT ALL
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU3', '10293847-56473829-10293847')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU3', '20384756-47382910-20384756')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU3', '30475869-38291047-30475869')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU3', '40567982-29182938-40567982')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU3', '50659173-18273645-50659173')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU3', '60742816-07364752-60742816')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU3', '70835927-96455861-70835927')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU3', '80928034-85546970-80928034')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU3', '11020141-74638089-11020141')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU3', '21113252-63729198-21113252')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU3', '31206363-52810207-31206363')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU3', '41399474-41901316-41399474')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU3', '51482585-30092425-51482585')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU3', '61575696-29183534-61575696')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU3', '71668707-18274643-71668707')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU3', '81751818-07365752-81751818')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU3', '91844929-96456861-91844929')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU3', '12938030-85547970-12938030')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU3', '23021141-74638089-23021141')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU3', '34114252-63729198-34114252')
SELECT 1 FROM DUAL;

-- -----------------------------------------------------------------------------
-- BANK_ACCOUNT_HU2 — Hungarian 2-part format: NNNNNNNN-NNNNNNNN (15 entries)
-- -----------------------------------------------------------------------------
INSERT ALL
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU2', '10293847-56473829')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU2', '20384756-47382910')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU2', '30475869-38291047')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU2', '40567982-29182938')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU2', '50659173-18273645')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU2', '60742816-07364752')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU2', '70835927-96455861')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU2', '80928034-85546970')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU2', '11020141-74638089')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU2', '21113252-63729198')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU2', '31206363-52810207')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU2', '41399474-41901316')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU2', '51482585-30092425')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU2', '61575696-29183534')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('BANK_ACCOUNT_HU2', '71668707-18274643')
SELECT 1 FROM DUAL;

-- -----------------------------------------------------------------------------
-- IBAN (20 entries — structurally plausible format, no real bank or account)
-- -----------------------------------------------------------------------------
INSERT ALL
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('IBAN', 'HU42 1177 3016 1234 5678 9000 0001')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('IBAN', 'HU93 1160 0006 9876 5432 1000 0002')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('IBAN', 'HU54 1177 3016 1357 2468 0000 0003')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('IBAN', 'HU61 1040 1042 1928 3746 5500 0004')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('IBAN', 'HU78 1030 4028 2837 4650 1000 0005')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('IBAN', 'DE89 3704 0044 1234 5678 90')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('IBAN', 'DE27 2004 1155 9876 5432 10')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('IBAN', 'GB29 NWBK 6016 1331 9268 19')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('IBAN', 'GB47 BARC 2032 6511 2345 67')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('IBAN', 'AT61 1904 3002 3457 3201')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('IBAN', 'AT83 2011 1829 1234 5678')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('IBAN', 'CH93 0076 2011 6238 5295 7')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('IBAN', 'CH56 0483 5012 3456 7800 9')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('IBAN', 'FR76 3000 6000 0112 3456 7890 189')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('IBAN', 'NL91 ABNA 0417 1643 00')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('IBAN', 'PL61 1090 1014 0000 0712 1981 2874')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('IBAN', 'SK31 1200 0000 1987 4263 7541')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('IBAN', 'CZ65 0800 0000 1920 0014 5399')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('IBAN', 'BE68 5390 0754 7034')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('IBAN', 'ES91 2100 0418 4502 0005 1332')
SELECT 1 FROM DUAL;

-- -----------------------------------------------------------------------------
-- EMAIL (20 entries)
-- -----------------------------------------------------------------------------
INSERT ALL
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('EMAIL', 'aldric.ashveil@aetherstone.io')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('EMAIL', 'caelindra.blackthorn@brightforge.net')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('EMAIL', 'draven.crestfall@crystalveil.com')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('EMAIL', 'eryndel.darkwater@dawnwatch.org')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('EMAIL', 'fyrath.embervale@embervault.net')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('EMAIL', 'galadwyn.frostmere@frostmantle.com')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('EMAIL', 'haervyn.grimhallow@goldenveil.io')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('EMAIL', 'ithrial.highwatch@highstone.org')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('EMAIL', 'jorethis.ironbrook@ironveil.net')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('EMAIL', 'kaelveth.jadestone@jadespire.com')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('EMAIL', 'lyranthos.kravenhold@kravenstone.io')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('EMAIL', 'morvindel.lightweave@lightforge.net')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('EMAIL', 'naelith.moonwhisper@moonvault.com')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('EMAIL', 'oribeth.nightglen@nightwatch.org')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('EMAIL', 'pyrindel.oakhaven@opalgate.net')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('EMAIL', 'quelithar.petravel@aetherstone.io')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('EMAIL', 'rhosgal.queensmere@brightforge.net')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('EMAIL', 'sylthari.ridgewood@crystalveil.com')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('EMAIL', 'thaevon.stonefall@dawnwatch.org')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('EMAIL', 'ulyndra.thornwick@embervault.net')
SELECT 1 FROM DUAL;

-- -----------------------------------------------------------------------------
-- DEPARTMENT (25 entries)
-- -----------------------------------------------------------------------------
INSERT ALL
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Arcane Research')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Binding & Contracts')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Crystal Analysis')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Deep Vault Operations')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Eldritch Compliance')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Forge Management')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Governance & Wards')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Holdings & Estates')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Interrealm Relations')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Judgement & Arbitration')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Keystep Operations')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Lore & Records')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Mystical Assessment')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Nullwork Security')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Outer Exchange')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Provisions & Supply')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Quarry & Assets')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Realm Development')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Spellcraft IT')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Treasury & Bonds')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Underwatch Audit')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Vaultkeeper Office')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Warden Services')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Xchange & Derivatives')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DEPARTMENT', 'Yearbook & Archives')
SELECT 1 FROM DUAL;

-- -----------------------------------------------------------------------------
-- NATIONAL_ID_HU — Hungarian-style national ID (szemelyigazolvany) format (15 entries)
-- Format: 2 letters + 6 digits + 2 letters  (clearly fictional)
-- -----------------------------------------------------------------------------
INSERT ALL
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_HU', 'AE293847XZ')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_HU', 'BF384756YW')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_HU', 'CG475869ZV')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_HU', 'DH567982AU')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_HU', 'EI659173BT')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_HU', 'FJ742816CS')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_HU', 'GK835927DR')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_HU', 'HL928034EQ')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_HU', 'IM020141FP')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_HU', 'JN113252GO')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_HU', 'KO206363HN')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_HU', 'LP399474IM')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_HU', 'MQ482585JL')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_HU', 'NR575696KK')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_HU', 'OS668707LJ')
SELECT 1 FROM DUAL;

-- -----------------------------------------------------------------------------
-- NATIONAL_ID_EU — Generic EU-style IDs (15 entries, various country patterns)
-- -----------------------------------------------------------------------------
INSERT ALL
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_EU', 'AT-8472936105')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_EU', 'AT-9283047216')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_EU', 'AT-0394158327')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_EU', 'DE-L4ASTF7XQ1')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_EU', 'DE-T7ZXKM3VR5')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_EU', 'DE-R2YQBN8WS6')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_EU', 'PL-ARX28473619')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_EU', 'PL-BQY39584720')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_EU', 'FR-1234567890123')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_EU', 'FR-9876543210987')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_EU', 'IT-RSSMRA85T10A562S')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_EU', 'IT-BNCGVN91R14F205K')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_EU', 'ES-12345678Z')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_EU', 'ES-87654321X')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('NATIONAL_ID_EU', 'UK-AB123456C')
SELECT 1 FROM DUAL;

-- -----------------------------------------------------------------------------
-- TAX_NUMBER — Tax/VAT number placeholders (15 entries)
-- -----------------------------------------------------------------------------
INSERT ALL
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('TAX_NUMBER', '12345678-2-41')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('TAX_NUMBER', '23456789-1-42')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('TAX_NUMBER', '34567890-2-43')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('TAX_NUMBER', '45678901-1-44')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('TAX_NUMBER', '56789012-2-41')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('TAX_NUMBER', 'HU12345678')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('TAX_NUMBER', 'HU87654321')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('TAX_NUMBER', 'DE123456789')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('TAX_NUMBER', 'DE987654321')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('TAX_NUMBER', 'GB123456789')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('TAX_NUMBER', 'FR12345678901')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('TAX_NUMBER', 'AT U12345678')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('TAX_NUMBER', 'NL123456789B01')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('TAX_NUMBER', 'PL1234567890')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('TAX_NUMBER', 'CZ12345678')
SELECT 1 FROM DUAL;

-- -----------------------------------------------------------------------------
-- DIAGNOSIS_CODE — ICD-10-style codes with fantasy condition names (20 entries)
-- -----------------------------------------------------------------------------
INSERT ALL
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DIAGNOSIS_CODE', 'Z14.891')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DIAGNOSIS_CODE', 'A27.193')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DIAGNOSIS_CODE', 'K82.471')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DIAGNOSIS_CODE', 'F48.271')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DIAGNOSIS_CODE', 'M47.821')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DIAGNOSIS_CODE', 'J44.191')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DIAGNOSIS_CODE', 'G43.811')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DIAGNOSIS_CODE', 'H35.521')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DIAGNOSIS_CODE', 'I42.371')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DIAGNOSIS_CODE', 'L51.291')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DIAGNOSIS_CODE', 'N18.571')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DIAGNOSIS_CODE', 'E11.841')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DIAGNOSIS_CODE', 'C34.121')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DIAGNOSIS_CODE', 'D64.891')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DIAGNOSIS_CODE', 'Q87.291')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DIAGNOSIS_CODE', 'R53.831')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DIAGNOSIS_CODE', 'S72.091')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DIAGNOSIS_CODE', 'T14.891')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DIAGNOSIS_CODE', 'U09.971')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DIAGNOSIS_CODE', 'V49.891')
SELECT 1 FROM DUAL;

-- -----------------------------------------------------------------------------
-- MEDICATION — Fantasy-name medications with realistic dose formats (20 entries)
-- -----------------------------------------------------------------------------
INSERT ALL
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('MEDICATION', 'Aethermycin 500 mg')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('MEDICATION', 'Brightovir 250 mg')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('MEDICATION', 'Crystaline 10 mg')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('MEDICATION', 'Dawnprazole 20 mg')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('MEDICATION', 'Embermab 100 mg/ml')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('MEDICATION', 'Frostidone 5 mg')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('MEDICATION', 'Goldenhexal 400 mg')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('MEDICATION', 'Highvastatin 40 mg')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('MEDICATION', 'Ironzolam 15 mg')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('MEDICATION', 'Jadelosartan 50 mg')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('MEDICATION', 'Kravenumab 150 mg')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('MEDICATION', 'Lightomycin 300 mg')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('MEDICATION', 'Moondipine 5 mg')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('MEDICATION', 'Nightmetol 850 mg')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('MEDICATION', 'Opalbiotic 750 mg')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('MEDICATION', 'Pearloxin 200 mg')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('MEDICATION', 'Queensilide 25 mg')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('MEDICATION', 'Ridgevirin 600 mg')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('MEDICATION', 'Silverantil 100 mg')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('MEDICATION', 'Thornazole 375 mg')
SELECT 1 FROM DUAL;

-- -----------------------------------------------------------------------------
-- DOCTOR_NAME (15 entries)
-- -----------------------------------------------------------------------------
INSERT ALL
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DOCTOR_NAME', 'Dr. Aldric Frostmere')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DOCTOR_NAME', 'Dr. Caelindra Blackthorn')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DOCTOR_NAME', 'Dr. Draven Embervale')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DOCTOR_NAME', 'Dr. Eryndel Moonwhisper')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DOCTOR_NAME', 'Dr. Fyrath Thornwick')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DOCTOR_NAME', 'Dr. Galadwyn Ironbrook')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DOCTOR_NAME', 'Dr. Haervyn Jadestone')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DOCTOR_NAME', 'Dr. Ithrial Silvermont')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DOCTOR_NAME', 'Dr. Jorethis Cloudveil')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DOCTOR_NAME', 'Dr. Kaelveth Ashveil')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DOCTOR_NAME', 'Dr. Lyranthos Ravenspire')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DOCTOR_NAME', 'Dr. Morvindel Highwatch')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DOCTOR_NAME', 'Dr. Naelith Grimhallow')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DOCTOR_NAME', 'Dr. Oribeth Stonefall')
    INTO T_ANON_TOY_POOL (CATEGORY, VALUE) VALUES ('DOCTOR_NAME', 'Dr. Pyrindel Valewatch')
SELECT 1 FROM DUAL;

COMMIT;
